# This file was generated by GoReleaser. DO NOT EDIT.
cask "hactl" do
  version "2026.5.1"

  on_macos do
    on_intel do
      sha256 "4696f17136bd857435550fe37649c0e704327975591880729ff8a9f6c67080a3"
      url "https://github.com/swifty99/hactl/releases/download/v#{version}/hactl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "88e01538d5941cbe40e121d3f632b116b0005d0e915a19845006f23eba795089"
      url "https://github.com/swifty99/hactl/releases/download/v#{version}/hactl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4cdd1ec818f4dcefbbf5442ae2823b71fb668919d15810f74224d9db4dc403e5"
      url "https://github.com/swifty99/hactl/releases/download/v#{version}/hactl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d799359fa76e53f740a4dee7701287142ba0640fa0ce8527824fb2bf3810c907"
      url "https://github.com/swifty99/hactl/releases/download/v#{version}/hactl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hactl"
  desc "Home Assistant CLI — built for agentic workflows"
  homepage "https://github.com/swifty99/hactl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hactl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hactl"]
    end
  end

  # No zap stanza required

end
