# This file was generated by GoReleaser. DO NOT EDIT.
cask "hactl" do
  version "2026.5.4"

  on_macos do
    on_intel do
      sha256 "d8e042cab406b5126c892aeeb541fcca4ced3467a7a7b701fa7769c58689cb84"
      url "https://github.com/swifty99/hactl/releases/download/v#{version}/hactl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "85f3b96f70b15579e3510e1b1c182164bded3b9b64cbab44684c197888dbe688"
      url "https://github.com/swifty99/hactl/releases/download/v#{version}/hactl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "534d30ca93e76113f7290e31c4344c17e80900f2bcb202235d36ce9f62e894b0"
      url "https://github.com/swifty99/hactl/releases/download/v#{version}/hactl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "01efdbf25c7ecf0981ea2dd0b2e097d6d3c9a341af23ae0674adcfd8553eb13d"
      url "https://github.com/swifty99/hactl/releases/download/v#{version}/hactl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hactl"
  desc "Home Assistant CLI — built for agentic workflows"
  homepage "https://github.com/swifty99/hactl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hactl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hactl"]
    end
  end

  # No zap stanza required

end
