# This file was generated by GoReleaser. DO NOT EDIT.
cask "hactl" do
  version "2026.5.3"

  on_macos do
    on_intel do
      sha256 "b245ee8f199453666150afda114fc7300045f3a6e35d2680a64dd8d56215e67d"
      url "https://github.com/swifty99/hactl/releases/download/v#{version}/hactl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "296ca277d3deb6ce1f841f7580343bc1d73d6a7830536dd9751479abe4a6c5b1"
      url "https://github.com/swifty99/hactl/releases/download/v#{version}/hactl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d1f5f93df597e359be72c60f40564acfc4f354a7e8b96bb429edc7faf5f0a6c7"
      url "https://github.com/swifty99/hactl/releases/download/v#{version}/hactl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ebe570c265a969c0b841cc188653b5eddd0fa6304224e894e7788b3dd2252067"
      url "https://github.com/swifty99/hactl/releases/download/v#{version}/hactl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hactl"
  desc "Home Assistant CLI — built for agentic workflows"
  homepage "https://github.com/swifty99/hactl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hactl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hactl"]
    end
  end

  # No zap stanza required

end
